---
knit: "bookdown::render_book"
title: "Tidy evaluation"
author: ["Lionel Henry", "Hadley Wickham"]

description: "The primary goal of this book is to get you up to speed with tidy evaluation and how to write functions around tidyverse pipelines and grammars."

github-repo: tidyverse/tidyeval
site: bookdown::bookdown_site
documentclass: book
---

# Welcome {-}

The primary goal of this book is to get you up to speed with tidy evaluation by showing you how to write functions using tidyverse pipelines and grammars. The book is written and organised so that you can quickly find the information you need to solve real world problems without having to "get" tidy eval first:

* The first chapter *Getting up to speed* is a quick introduction to the main pattern used in all tidy eval functions: **quote and unquote**.

* The *Cookbooks* sections are organised by common tasks for the dplyr and ggplot2 packages.

Though this is a work in progress, we hope you'll find this bookdown valuable for programming with tidyverse interfaces.


## Other resources {-}

You may also be interested in:

* __"[Tidy eval in 5 minutes](https://www.youtube.com/watch?v=nERXS3ssntw)"__ is a quick 5 minutes video that explains the big ideas behind tidy evaluation. It's a great way to get an overview of concepts before diving in other tutorials.

* __"[Tidy eval webinar](https://resources.rstudio.com/webinars/tidyeval)"__ is a one hour tutorial video on tidy evaluation.

* __"[The second edition of Advanced R](http://adv-r.hadley.nz/)"__ which includes a whole chapter on meta programming with tidy eval.
